.TH virtualizm-wsproxy 1 "MARCH 2020" virtualizm-wsproxy "Websockify Daemon Manual"
.SH NAME
virtualizm-wsproxy \- proxify WebSocket connections to TCP
.SH SYNOPSIS
.B virtualizm-wsproxy
[\fI\,-h\/\fR] [\fI\,-i\/\fR listen_ip] [\fI\,-p\/\fR port]
.SH DESCRIPTION
.PP
Simple daemon to proxify WebSocket connections to TCP
.SH OPTIONS
.PP
.TP
\fB\-h\fR
print help
.TP
\fB\-i\fR listen_ip
IP adddress for WS socket
.TP
\fB\-p\fR port
port for WS socket
.TP
\fB\-v\fR
enable verbose mode. -v to print WS handshake data. -vv to print traffic events in addition
.TP
\fB\-s\fR, \fB\-\-src\-whitelist\fR list_def
restrict allowed source IP addresses for incoming WebSocket connections (comma-separated networks list in CIDR notation)
.TP
\fB\-d\fR, \fB\-\-dst\-whitelist\fR list_def
restrict allowed destination IP addresses for outgoing TCP connections (comma-separated networks list in CIDR notation)
