.TH websockify 1 "MARCH 2020" websockify "Websockify Daemon Manual"
.SH NAME
websockify \- proxify WebSocket connections to TCP
.SH SYNOPSIS
.B websockify
[\fI\,-h\/\fR] [\fI\,-i\/\fR listen_ip] [\fI\,-p\/\fR port]
.SH DESCRIPTION
.PP
Simple daemon to proxify WebSocket connections to TCP
.SH OPTIONS
.PP
.TP
\fB\-h\fR
print help
.TP
\fB\-i\fR listen_ip
IP adddress for WS socket
.TP
\fB\-p\fR port
port for WS socket
